# Generated by Django 4.1.2 on 2022-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="file",
            field=models.FileField(default=None, upload_to="plan_files"),
            preserve_default=False,
        ),
    ]
