# Generated by Django 4.1.2 on 2022-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0003_alter_plan_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="original_file_name",
            field=models.CharField(default="xxx", max_length=100),
            preserve_default=False,
        ),
    ]
