# Generated by Django 4.1.2 on 2022-10-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0004_plan_original_file_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("red", models.IntegerField(default=0)),
                ("green", models.IntegerField(default=0)),
                ("blue", models.IntegerField(default=0)),
                ("alpha", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlotableStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_name", models.CharField(max_length=100)),
                ("line_thickness", models.IntegerField()),
                (
                    "fill_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plotablestyle_fill",
                        to="plan_visualiser_django.color",
                    ),
                ),
                (
                    "font",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plan_visualiser_django.font",
                    ),
                ),
                (
                    "line_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plotablestyle_line",
                        to="plan_visualiser_django.color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("width", models.FloatField(default=30)),
                ("max_height", models.FloatField(default=20)),
                ("include_title", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visualiser_django.plan",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("red__gte", 0), ("red__lt", 255)),
                name="Red component must be between 0 and 255 (inclusive)",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("green__gte", 0), ("green__lte", 255)),
                name="Green component must be between 0 and 255 (inclusive)",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("blue__gte", 0), ("blue__lte", 255)),
                name="Blue component must be between 0 and 255 (inclusive)",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("alpha__gte", 0), ("alpha__lte", 1)),
                name="Alpha value must be between 0 and 1",
            ),
        ),
    ]
