# Generated by Django 4.1.2 on 2022-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0005_color_font_plotablestyle_planvisual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="name",
            field=models.CharField(default="Color name", max_length=100),
            preserve_default=False,
        ),
    ]
