# Generated by Django 4.1.2 on 2022-10-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0006_color_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
