# Generated by Django 4.1.2 on 2022-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0007_alter_color_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="color",
            name="Red component must be between 0 and 255 (inclusive)",
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("red__gte", 0), ("red__lte", 255)),
                name="Red component must be between 0 and 255 (inclusive)",
            ),
        ),
    ]
