# Generated by Django 4.1.2 on 2023-01-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visualiser_django",
            "0008_remove_color_red component must be between 0 and 255 (inclusive)_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SwimlaneForVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swim_lane_name", models.CharField(max_length=50)),
                (
                    "plan_visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visualiser_django.planvisual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_unique_id", models.CharField(max_length=50)),
                (
                    "swimlane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visualiser_django.swimlaneforvisual",
                    ),
                ),
                (
                    "visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visualiser_django.planvisual",
                    ),
                ),
            ],
        ),
    ]
