# Generated by Django 4.1.2 on 2023-01-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0009_swimlaneforvisual_visualactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotableShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotableShapeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PlotableShapeAttributesRectangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "plotable_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visualiser_django.plotableshape",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotableShapeAttributesDiamond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "plotable_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visualiser_django.plotableshape",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plotableshape",
            name="shape_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.plotableshapetype",
            ),
        ),
    ]
