# Generated by Django 4.1.2 on 2023-01-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visualiser_django",
            "0011_horizontalalignmenttype_verticalalignmenttype",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TextFlowType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_flow_name",
                    models.CharField(
                        choices=[
                            ("LFLOW", "Align right, flow to left"),
                            ("RFLOW", "Align left, flow to right"),
                            ("WSHAPE", "Align centre, flow left/right"),
                            ("CLIPPED", "Align centre, clipped to shape"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="horizontalalignmenttype",
            name="horizontal_alignment_name",
            field=models.CharField(
                choices=[("LEFT", "Left"), ("CENTER", "Center"), ("RIGHT", "Right")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verticalalignmenttype",
            name="vertical_alignment_name",
            field=models.CharField(
                choices=[("TOP", "Top"), ("MIDDLE", "Middle"), ("BOTTOM", "Bottom")],
                max_length=20,
            ),
        ),
    ]
