# Generated by Django 4.1.2 on 2023-01-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0012_textflowtype_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HorizontalAlignmentType", new_name="TextHorizontalAlignmentType",
        ),
        migrations.RenameModel(
            old_name="VerticalAlignmentType", new_name="TextVerticalAlignmentType",
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="height_in_tracks",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="plotable_shape",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.plotableshape",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="vertical_positioning_type",
            field=models.CharField(
                choices=[
                    ("", "Specify track #"),
                    ("", "Specify relative to last positioned activity"),
                    ("", "Automatic positioning"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="vertical_positioning_value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
