# Generated by Django 4.1.2 on 2023-01-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visualiser_django",
            "0013_rename_horizontalalignmenttype_texthorizontalalignmenttype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="visualactivity",
            name="plotable_style",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.plotablestyle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="text_flow",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.textflowtype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="text_horizontal_alignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.texthorizontalalignmenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualactivity",
            name="text_vertical_alignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.textverticalalignmenttype",
            ),
            preserve_default=False,
        ),
    ]
