# Generated by Django 4.1.2 on 2023-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0014_visualactivity_plotable_style_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualactivity", options={"verbose_name_plural": "visual activities"},
        ),
        migrations.AlterField(
            model_name="visualactivity",
            name="text_flow",
            field=models.CharField(
                choices=[
                    ("LFLOW", "Align right, flow to left"),
                    ("RFLOW", "Align left, flow to right"),
                    ("WSHAPE", "Align centre, flow left/right"),
                    ("CLIPPED", "Align centre, clipped to shape"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visualactivity",
            name="text_horizontal_alignment",
            field=models.CharField(
                choices=[("LEFT", "Left"), ("CENTER", "Center"), ("RIGHT", "Right")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visualactivity",
            name="text_vertical_alignment",
            field=models.CharField(
                choices=[("TOP", "Top"), ("MIDDLE", "Middle"), ("BOTTOM", "Bottom")],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(name="TextFlowType",),
        migrations.DeleteModel(name="TextHorizontalAlignmentType",),
        migrations.DeleteModel(name="TextVerticalAlignmentType",),
    ]
