# Generated by Django 4.1.2 on 2023-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0015_alter_visualactivity_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visualactivity",
            old_name="plan_unique_id",
            new_name="unique_id_from_plan",
        ),
        migrations.AlterField(
            model_name="visualactivity",
            name="vertical_positioning_type",
            field=models.CharField(
                choices=[
                    ("TRACK", "Specify track #"),
                    ("REL_TRACK", "Specify relative to last positioned activity"),
                    ("AUTO", "Automatic positioning"),
                ],
                max_length=20,
            ),
        ),
    ]
