# Generated by Django 4.1.2 on 2023-01-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visualiser_django",
            "0016_rename_plan_unique_id_visualactivity_unique_id_from_plan_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("FLOAT", "Decimal number"),
                            ("STR", "String"),
                            ("DATE", "Date (without time)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="PlanFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanFieldMappingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="PlanMappedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_field_name", models.CharField(max_length=50)),
                (
                    "input_field_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("FLOAT", "Decimal number"),
                            ("STR", "String"),
                            ("DATE", "Date (without time)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plan_field",
                    models.ManyToManyField(
                        through="plan_visualiser_django.PlanFieldMapping",
                        to="plan_visualiser_django.planfield",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planfieldmapping",
            name="mapping_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.planfieldmappingtype",
            ),
        ),
        migrations.AddField(
            model_name="planfieldmapping",
            name="plan_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.planfield",
            ),
        ),
        migrations.AddField(
            model_name="planfieldmapping",
            name="plan_mapped_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.planmappedfield",
            ),
        ),
    ]
