# Generated by Django 4.1.2 on 2023-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visualiser_django",
            "0017_planfield_planfieldmapping_planfieldmappingtype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="planfield",
            name="required_flag",
            field=models.BooleanField(default=True),
        ),
    ]
