# Generated by Django 4.1.2 on 2023-01-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0019_planfield_sort_index"),
    ]

    operations = [
        migrations.RemoveField(model_name="planmappedfield", name="plan_field",),
        migrations.AddField(
            model_name="planmappedfield",
            name="mapped_field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.planfield",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planmappedfield",
            name="plan_field_mapping_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.planfieldmappingtype",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="PlanFieldMapping",),
    ]
