# Generated by Django 4.1.5 on 2023-01-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visualiser_django", "0021_plan_unique_filename_for_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="filetype",
            name="plan_field_mapping_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visualiser_django.planfieldmappingtype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Decimal number"),
                    ("STR", "String"),
                    ("STR_nnd", "String of form nnd where nn is an integer value"),
                    ("DATE", "Date (without time)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planmappedfield",
            name="input_field_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Decimal number"),
                    ("STR", "String"),
                    ("STR_nnd", "String of form nnd where nn is an integer value"),
                    ("DATE", "Date (without time)"),
                ],
                max_length=20,
            ),
        ),
    ]
